version: '3'
services:
      
  rabbit:
    image: rabbitmq:3.8-management
    ports:   
      - "5671-5672:5671-5672"
      - "15672:15672"
      - "4369:4369"
      - "15671:15671" 

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: semaphore
      MYSQL_USER: semaphore
      MYSQL_PASSWORD: semaphore
    #volumes:
    #  - /tmp/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

      
  semaphore:
    image: ansiblesemaphore/semaphore
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphore
      SEMAPHORE_DB_HOST: mysql
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /etc/semaphore
      SEMAPHORE_ADMIN_PASSWORD: password
      SEMAPHORE_ADMIN_NAME: "Developer"
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_WEB_ROOT: http://0.0.0.0:3000
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      
      
  logspout:
    ports: 
      - "30002:80"   
    volumes:
      - /etc/hostname:/etc/host_hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      publish: "127.0.0.1:30002:80"
    image: gliderlabs/logspout:latest
        
      
  mongo:
    image: mongo:4
    ports:
      - "27017:27017"         
            
    
  #manager:
    #depends_on:
      #- rabbit
      #- mongo
      #- sure-tosca
    #image: manager:3.0.0
    #environment:
      #RABBITMQ_HOST: rabbit
      #MONGO_HOST: mongo
      #SURE_TOSCA_BASE_PATH: http://sure-tosca:8081/tosca-sure/1.0.0
    #ports:
      #- "30000:8080"       
            
  sure-tosca:
    image: sure-tosca:3.0.0
    ports: 
      - "8081:8081"
    
  planner:
    depends_on:
      - rabbit
      - sure-tosca
    image: planner:3.0.0
    environment:
      RABBITMQ_HOST: rabbit
    
  #provisioner:
    #depends_on:
      #- rabbit
      #- sure-tosca
    #image: provisioner:3.0.0
    #environment:
      #RABBITMQ_HOST: rabbit      
      #SURE_TOSCA_BASE_PATH: http://sure-tosca:8081/tosca-sure/1.0.0
    
  #deployer:
    #depends_on:
      #- rabbit
      #- sure-tosca
    #image: deployer:3.0.0
    #environment:
      #RABBITMQ_HOST: rabbit           
      #SURE_TOSCA_BASE_PATH: http://sure-tosca:8081/tosca-sure/1.0.0

      
#volumes:
  #db-data:
