apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels: 
    name: mongo
spec: 
  containers: 
    - resources:
        limits :
          cpu: 0.5
      image: mongo:4
      name: mongo
      env:
        - name: VAR
          value: VAL
      #ports: 
        #- containerPort: 27017
          #name: mongo
      volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /var/lib/mongo
  volumes:
    - name: mongo-persistent-storage
      gcePersistentDisk:
        pdName: mongo-disk
        fsType: ext4
