apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
  labels: 
    name: rabbitmq
spec: 
  containers: 
    - resources:
        limits :
          cpu: 0.5
      image: rabbitmq:3-management
      name: rabbitmq
      env:
        - name: VAR
          value: VAL
      #ports: 
        #- containerPort: 15672
          #name: rabbitmq
