version: '3'

services:
    graphite:
        restart: always
        image: vladwing/graphite
        volumes:
         - graphite_data:/opt/graphite/storage
        environment:
         - VIRTUAL_HOST=graphite.beia.switch
        networks:
         - web
         - graphite
    grafana:
        restart: always
        image: grafana/grafana
        environment:
         - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-secret}
         - VIRTUAL_HOST=grafana.beia.switch
        volumes:
         - grafana_data:/var/lib/grafana
        depends_on:
         - graphite
        networks:
         - web
    monitoring_server:
        image: salmant/ul_monitoring_server_container_image
        ports:
         - "8080:8080"
         - "4242:4242"
         - "4245:4245"
         - "7199:7199"
         - "7000:7000"
         - "7001:7001"
         - "9160:9160"
         - "9042:9042"
         - "8012:8012"
         - "61621:61621"
        environment:
         - MONITORING_SERVER=monitoring_server
         - VIRTUAL_HOST=jcatascopia.beia.switch
         - VIRTUAL_PORT=8080
        networks:
         - asap
         - web
    monitoring_adapter:
        restart: always
        image: beia/monitoring_adapter
        environment:
         - GRAPHITE_SERVER=graphite
         - MONITORING_PREFIX=eu.beia.switch
         - MONITORING_SERVER=${MONITORING_SERVER:-monitoring_server}
        depends_on:
         - graphite
         - monitoring_server
        networks:
         - graphite
         - data
         - asap
    data_collector:
        image: beia/data_collector
        environment:
         # - CONFIG=config
         - STATSD_HOST=monitoring_adapter
        depends_on:
         # - config
         - monitoring_adapter
        networks:
         # - config
         - data
    alerter:
        image: beia/alerter
        environment:
          # - CONFIG=config
          - STATSD_HOST=monitoring_adapter
          - VIRTUAL_HOST=alerter.beia.switch
          - NOTIFICATION_SERVICE=notify
        depends_on:
         - notify
         # - config
        networks:
         # - config
         - web
         - data
    # config:
    #     image: beia/config_manager
    #     environment:
    #      - TOSCA_URL=${TOSCA_URL:-http://www.google.com}
    #     networks:
    #      - config
    web:
        image: jwilder/nginx-proxy
        ports:
         - "80:80/tcp"
        volumes:
         - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
         - web
    notify:
        image: beia/notify
        environment:
        depends_on:
         - monitoring_adapter
         - notify_asterisk
         - notify_redis
        environment:
        # - CONFIG=config
         - ARI_URL=http://notify_asterisk:8088
         - ARI_USERNAME=ari_user
         - ARI_PASSWORD=ari_secret
         - REDIS_HOST=notify_redis
         - REDIS_PORT=6379
         - DEFAULT_SIP=sipserver
         - MONITORING_ADAPTER=monitoring_adapter
        networks:
         # - config
         - data
         - sip
    notify_asterisk:
        image: beia/asterisk
        environment:
         - SIP_USERNAME=${SIP_USERNAME}
         - SIP_HOST=${SIP_HOST}
         - SIP_PORT=${SIP_PORT:-26999}
         - SIP_SECRET=${SIP_SECRET}
         - SIP_EXTENSION=${SIP_EXTENSION}
         - SIP_PEERNAME=sipserver
         - ARI_USERNAME=ari_user
         - ARI_SECRET=ari_secret
        networks:
         - sip
    notify_redis:
        image: redis:alpine
        networks:
         - sip
volumes:
 graphite_data:
 grafana_data:
networks:
 # config:
 data:
 web:
 graphite:
 sip:
 asap:
