version: '3'
services:
  server:
    image: salmant/ul_monitoring_server_container_image2
    ports:
      - "8080:8080"
      - "4242:4242"
      - "4245:4245"
      - "7199:7199"
      - "7000:7000"
      - "7001:7001"
      - "9160:9160"
      - "9042:9042"
      - "8012:8012"
      - "61621:61621"
    environment:
      - "MONITORING_SERVER=server"

  agent:
    image: salmant/monitoring_agent
    deploy: {replicas: 10}
    depends_on: [server]
    command: --monitoringServerIP=server