tosca_definitions_version: tosca_simple_yaml_1_0
repositories:
 docker_hub: https://hub.docker.com/

imports:
- nodes: https://raw.githubusercontent.com/skoulouzis/DRIP/DRIP_3.0/TOSCA/types/nodes.yaml
- capabilities: https://raw.githubusercontent.com/skoulouzis/DRIP/DRIP_3.0/TOSCA/types/capabilities.yaml
- policies: https://raw.githubusercontent.com/skoulouzis/DRIP/DRIP_3.0/TOSCA/types/policies.yaml

topology_template:
  node_templates:
    wordpress:
      type: tosca.nodes.ARTICONF.Container.Application.Docker
      requirements:
        - service:
            node: mysql
            relationship:
                #type: tosca.relationships.ConnectsTo
                type: tosca.relationships.DependsOn
      artifacts:
        image:
          file: wordpress:latest
          type: tosca.artifacts.Deployment.Image.Container.Docker
          repository: docker_hub
      properties:
        ports: 
          - "8000:80"
        environment:
          WORDPRESS_DB_HOST: mysql:3306
          WORDPRESS_DB_USER: wordpress
          WORDPRESS_DB_PASSWORD: wordpress
          WORDPRESS_DB_NAME: wordpress
      requirements:
      - host:
          capability: tosca.capabilities.ARTICONF.Orchestrator
          node: heidi_kubernetes
          relationship: tosca.relationships.HostedOn          
          
    mysql:
      artifacts:
        image:
          file: mysql:5.7
          repository: docker_hub
          type: tosca.artifacts.Deployment.Image.Container.Docker
      properties:
        environment:
          MYSQL_DATABASE: wordpress
          MYSQL_PASSWORD: wordpress
          MYSQL_ROOT_PASSWORD: somewordpress
          MYSQL_USER: wordpress
        volumes:
        - db_data:/var/lib/mysql
      requirements:
      - host:
          capability: tosca.capabilities.ARTICONF.Orchestrator
          node: heidi_kubernetes
          relationship: tosca.relationships.HostedOn
      type: tosca.nodes.ARTICONF.Container.Application.Docker        
      
    heidi_kubernetes:
      interfaces:
        Standard:
          create: interfaces/playbooks/kubernetes_install.yaml
      requirements:
      - host:
          capability: tosca.capabilities.Scalable
          node: beverly_topology
          relationship: tosca.relationships.HostedOn
      - host:
          capability: tosca.capabilities.Compute
          node: beverly_topology
          relationship: tosca.relationships.HostedOn
      type: tosca.nodes.ARTICONF.Orchestrator.Kubernetes      
      
    beverly_topology:
      interfaces:
        Standard:
          create: dumy.yaml
      properties:
        domain: UvA (Amsterdam, The Netherlands) XO Rack
        name: name
        provider: ExoGeni
      requirements:
      - vm:
          capability: tosca.capabilities.ARTICONF.VM
          node: nancy_compute
          relationship: tosca.relationships.DependsOn
      type: tosca.nodes.ARTICONF.VM.topology
      
    nancy_compute:
      interfaces:
        Standard:
          create: dumy.yaml
      properties:
        cpu_frequency: 2.9 GHz
        disk_size: 25000 MB
        host_name: vm
        mem_size: 3000 MB
        num_cpus: 1
      type: tosca.nodes.ARTICONF.VM.Compute
