tosca_definitions_version: tosca_simple_yaml_1_0

imports:
  - nodes: https://raw.githubusercontent.com/skoulouzis/DRIP/DRIP_3.0/TOSCA/types/nodes.yaml
  - data: https://raw.githubusercontent.com/skoulouzis/CONF/DRIP_3.0/TOSCA/types/data.yml
  - capabilities: https://raw.githubusercontent.com/skoulouzis/DRIP/DRIP_3.0/TOSCA/types/capabilities.yaml
  - policies: https://raw.githubusercontent.com/skoulouzis/DRIP/DRIP_3.0/TOSCA/types/policies.yaml
  - interfaces: https://raw.githubusercontent.com/skoulouzis/DRIP/DRIP_3.0/TOSCA/types/interfaces.yml
  
repositories:
  docker_hub: https://hub.docker.com/  

description: >
  TOSCA example
  

topology_template:

  node_templates:        
    mongo:
        type: tosca.nodes.ARTICONF.Container.Application.Docker
        properties:
            ports: 
            - "27017:27017"   
            volumes:
                - db_data:/var/lib/mongo
            environment:
                MONGO_INITDB_ROOT_PASSWORD: rootPassword
                MONGO_INITDB_DATABASE: databaseName
                MONGO_INITDB_ROOT_USERNAME: rootUser
                MONGO_USERNAME: databaseUser
                MONGO_PASSWORD: password
        artifacts:
            image:
                type: tosca.artifacts.Deployment.Image.Container.Docker
                file: lakshminp/mongo:4.2.1
                repository: docker_hub    
                
        
    logspout:
        type: tosca.nodes.ARTICONF.Container.Application.Docker
        properties:
            ports: 
            - "8000:80"   
            volumes:
                - /etc/hostname:/etc/host_hostname:ro
                - /var/run/docker.sock:/var/run/docker.sock
            environment:
                publish: "127.0.0.1:8000:80"
        artifacts:
            image:
                type: tosca.artifacts.Deployment.Image.Container.Docker
                file: gliderlabs/logspout:latest
                repository: docker_hub                    
                
  policies:
    - scalability:
        type: tosca.policies.ARTICONF.Performance.CPU
        targets: [ mongo ]
        properties:
            constraint_name: cpu_load
            max_value: 90
    - faultTolerance:
        type: tosca.policies.ARTICONF.FaultTolerance
        targets: [ mongo ]     
        properties:
            level: 1
              
            
        
        
          
          
          
          
