tosca_definitions_version: "tosca_simple_yaml_1_0"
topology_template:
  node_templates:
    compute:
      properties:
        disk_size: "50000 MB"
        mem_size: "6000 MB"
        num_cores: 2.0
        os: "Ubuntu 18.04"
        user_name: "vm_user"
      interfaces:
        Standard:
          create: "dumy.yaml"
      type: "tosca.nodes.ARTICONF.VM.Compute"
      attributes:
        user_key_pair:
          protocol: "ssh"
          keys:
            public_key: "c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFBZ1FDVnlpOVNZWitKTnp0ZG9maUM5WXI4RkhHZWJDdHdPUGl0bTFXVmNTL1pPM05tQXhXbXg1RGRDMUI4MU5GZEVWZEt2Nng2N0diSjI2SEplREhIMU9pMmt3aExDQzM5R0dZNmxPSjh4U0hKMjFJVXVydTRCaGk5STNGSlZ0Q1o0ckhIUGsvcjhkaQ1BrNjc1SllkSERFN0ZUbWpUN0lnOGptdzk0dThYZFpRPT0gYXV0byBnZW5lcmF0ZWQgdXNlciBhY2NlZXMga2V5cwo="
            private_key: "LS0tLS1CRUdJTiBSU0EgUFJJVkUkzRkpWdENaNHJISFBrL3I4ZGlJQkNQazY3NUpZZEhERTdGVG1qVDdJZzhqbXc5NHU4WGRaUUlEQVFBQgpBb0dBYXVhazV6SnMzVXpodlcwL0lwZUMzV3pwdVpxUlZjSVRHRE5uM1FPdWxtWnJjVDU2VVZEVC9pMTQvOTRTCm5VMG04MTNnQnNwNGdVK1NJMnI0ZkJsakN2RjNEYU9KN1VCUTR5OGpEbW5aUGdrK2ljTUQ2dC9SYnNLZzNPRjgKZ0pFeVN3NFF6UGtTZEJ3Z0JIUnZ3bnA4Z1BtUGxmYWRRCBSU0EgUFJJVkFURSBLRVktLS0tLQo="
        public_ip: "XXX.XXX.XXX.XXX"
        role: "master"
        node_type: "XOLarge"
        root_key_pair:
          protocol: "ssh"
          keys:
            public_key: "c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJDWmRRN2JvQ05VNkhWTndRPT0ga2V5UGFpci1iNWUxYTRjMC01ZjA5LTQyMGMtODQ1Yi04YTIyYmJjOWUxMGIK"
            private_key: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlDWEFJQkFBS0JnUUNDV04vM3ZVaDVreHhDNnBJZnhuUWE3V3VmWUplbmswbkxKYjFGQU1pN0gzOE1VYnBKCkE3UERwck9SbGhiTEU5ZVVsY1MwakE3Qmp1NXdsVkxlWi8rSjIzK2Z2UHdvb2FIQ0kvVXNiZ3ZFc05sZVhwdmwQ5ODF3dTNlTFB1WnBpWjNKCk93am1TR0pMQWtFQXFQWFJUMzVlU2kzQXBQRFlWQllYZnQ0NlByYWVHOGNSdkpTMFhYSS9vZWhuYmxZRngwZGsKWVQrUjcwajBSQk1TQ0YrVVdSaUlKdlVRR1lXSTBTa29vd0pCQUo0Slo1aXRwNGRtNzUxZlF5K2JsUEp6MjZzUQTlljZkN3R2NubGIrNnVWdQplY2R6dHRianBrbjBzTXdmdGwvL3kyNXl2L3JSdlpmWHRCMzUvNW9ZNUdrPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo="
        host_name: "vm1"
    compute_1:
      properties:
        disk_size: "50000 MB"
        mem_size: "6000 MB"
        num_cores: 2
        os: "Ubuntu 18.04"
        user_name: "vm_user"
      interfaces:
        Standard:
          create: "dumy.yaml"
      type: "tosca.nodes.ARTICONF.VM.Compute"
    kubernetes:
      properties:
        min_masters_num: 1
        min_workers_num: 1
      requirements:
      - host:
          capability: "tosca.capabilities.ARTICONF.VM.topology"
          node: "topology"
          relationship: "tosca.relationships.HostedOn"
      interfaces:
        Standard:
          create:
            inputs:
              inventory-file: "k8s_hosts"
              playbook: "https://raw.githubusercontent.com/skoulouzis/CONF/DRIP_3.0/ansible_playbooks/install_k8s.yml"
      type: "tosca.nodes.ARTICONF.Orchestrator.Kubernetes"
    logspout:
      properties:
        environment:
          publish: "127.0.0.1:8000:80"
        ports:
        - "8000:80"
        volumes:
        - "/etc/hostname:/etc/host_hostname:ro"
        - "/var/run/docker.sock:/var/run/docker.sock"
      requirements:
      - host:
          capability: "tosca.capabilities.ARTICONF.Orchestrator"
          node: "kubernetes"
          relationship: "tosca.relationships.HostedOn"
      type: "tosca.nodes.ARTICONF.Container.Application.Docker"
      artifacts:
        image:
          file: "gliderlabs/logspout:latest"
          repository: "docker_hub"
          type: "tosca.artifacts.Deployment.Image.Container.Docker"
    mysql:
      properties:
        environment:
          MYSQL_DATABASE: "wordpress"
          MYSQL_PASSWORD: "wordpress"
          MYSQL_ROOT_PASSWORD: "somewordpress"
          MYSQL_USER: "wordpress"
        ports:
        - "3306:3306"
        volumes:
        - "db_data:/var/lib/mysql"
      requirements:
      - host:
          capability: "tosca.capabilities.ARTICONF.Orchestrator"
          node: "kubernetes"
          relationship: "tosca.relationships.HostedOn"
      type: "tosca.nodes.ARTICONF.Container.Application.Docker"
      artifacts:
        image:
          file: "mysql:5.7"
          repository: "docker_hub"
          type: "tosca.artifacts.Deployment.Image.Container.Docker"
    topology:
      properties:
        domain: "UvA (Amsterdam, The Netherlands) XO Rack"
        provider: "ExoGENI"
      requirements:
      - vm:
          capability: "tosca.capabilities.ARTICONF.VM"
          node: "compute"
          relationship: "tosca.relationships.DependsOn"
      - vm:
          capability: "tosca.capabilities.ARTICONF.VM"
          node: "compute_1"
          relationship: "tosca.relationships.DependsOn"
      interfaces:
        CloudsStorm:
          provision:
            inputs:
              code_type: "SEQ"
              object_type: "SubTopology"
      type: "tosca.nodes.ARTICONF.VM.topology"
      attributes:
        credential:
          cloud_provider_name: "ExoGENI"
          keys:
            keystore: "/u3+7QAAAAIAAAABAAAAAQAEZ2VuaQAAAWt5eo+WAAAFAzCCBP8wDgYKKwYBBAEqAhEBAQUABIIE6+QI4jVyvo+477on8OaF0nwbPvG5QFgYpQDTzX0RDKG5egGch+rxMOHpWerYCmsS5XlHMnUBvqE6lr/H8VieuqwSH97mMwEcwvIdj52nQIuroQsTZampoxYu01"
          token: "password"
          token_type: "password"
          user: "user"
        status: "running"
    wordpress:
      properties:
        environment:
          WORDPRESS_DB_HOST: "mysql:3306"
          WORDPRESS_DB_NAME: "wordpress"
          WORDPRESS_DB_PASSWORD: "wordpress"
          WORDPRESS_DB_USER: "wordpress"
        ports:
        - "8000:80"
      requirements:
      - service:
          node: "mysql"
          relationship:
            type: "tosca.relationships.DependsOn"
      - host:
          capability: "tosca.capabilities.ARTICONF.Orchestrator"
          node: "kubernetes"
          relationship: "tosca.relationships.HostedOn"
      type: "tosca.nodes.ARTICONF.Container.Application.Docker"
      artifacts:
        image:
          file: "wordpress:latest"
          repository: "docker_hub"
          type: "tosca.artifacts.Deployment.Image.Container.Docker"
  policies:
  - scalability:
      properties:
        constraint_name: "cpu_load"
        max_value: 90
      targets:
      - "wordpress"
      type: "tosca.policies.ARTICONF.Performance.CPU"
  - faultTolerance:
      properties:
        level: 1
      targets:
      - "mysql"
      type: "tosca.policies.ARTICONF.FaultTolerance"
description: "TOSCA example"
imports:
- nodes: "https://raw.githubusercontent.com/skoulouzis/DRIP/DRIP_3.0/TOSCA/types/nodes.yaml"
- data: "https://raw.githubusercontent.com/skoulouzis/CONF/DRIP_3.0/TOSCA/types/data.yml"
- capabilities: "https://raw.githubusercontent.com/skoulouzis/DRIP/DRIP_3.0/TOSCA/types/capabilities.yaml"
- policies: "https://raw.githubusercontent.com/skoulouzis/DRIP/DRIP_3.0/TOSCA/types/policies.yaml"
- interfaces: "https://raw.githubusercontent.com/skoulouzis/DRIP/DRIP_3.0/TOSCA/types/interfaces.yml"
