tosca_definitions_version: tosca_simple_yaml_1_0

imports:
  - nodes: https://raw.githubusercontent.com/skoulouzis/DRIP/DRIP_3.0/TOSCA/types/nodes.yaml
  - data: https://raw.githubusercontent.com/skoulouzis/CONF/DRIP_3.0/TOSCA/types/data.yml
  - capabilities: https://raw.githubusercontent.com/skoulouzis/DRIP/DRIP_3.0/TOSCA/types/capabilities.yaml
  - policies: https://raw.githubusercontent.com/skoulouzis/DRIP/DRIP_3.0/TOSCA/types/policies.yaml
  - interfaces: https://raw.githubusercontent.com/skoulouzis/DRIP/DRIP_3.0/TOSCA/types/interfaces.yml
  
repositories:
  docker_hub: https://hub.docker.com/  

description: >
  TOSCA example
  

topology_template:

  node_templates:        
    mongo:
        type: tosca.nodes.ARTICONF.Container.Application.Docker
        properties:
            ports: 
            - "30001:27017"   
            volumes:
                - db-data:/data/db
            environment:
                ROOT_PASSWORD: somewordpress
                DATABASE: db
                USER: user
                PASSWORD: passwd
        artifacts:
            image:
                type: tosca.artifacts.Deployment.Image.Container.Docker
                file:  mongo:3
                repository: docker_hub     
                
  policies:
    - scalability:
        type: tosca.policies.ARTICONF.Performance.CPU
        targets: [ mongo ]
        properties:
            constraint_name: cpu_load
            max_value: 90
    - faultTolerance:
        type: tosca.policies.ARTICONF.FaultTolerance
        targets: [ mongo ]     
        properties:
            level: 1
