---
- hosts: all
  tasks:
  - name: install sysbench
    apt: name="{{ item }}" update_cache=yes state=latest
    with_items: [phoronix-test-suite, sysbench, expect, git, python-pexpect]
    become: true
  - {name: Phoronix-test-suite accept User Agreement, command: 'expect -c "spawn phoronix-test-suite;
      expect \"Do you agree to these terms and wish to proceed \(Y/n\):\"; send \"Y
      \"; expect \"Enable anonymous usage / statistics reporting \(Y/n\):\"; send
      \"n \"; expect \"Enable anonymous statistical reporting of installed software
      / hardware \(Y/n\):\"; send \"n \"; interact;"', become: true}
  - {name: Install stream, command: phoronix-test-suite install-test stream, become: true}
  - {name: Install iozone, command: phoronix-test-suite install-test iozone, become: true}
  - {name: Count vCPU, command: nproc, register: vcpunumber, become: true}
  - {debug: 'msg="{{ vcpunumber.stdout }}"'}
  - {name: Run sysbench, command: 'sysbench --test=cpu --cpu-max-prime=100000 --num-threads={{
      vcpunumber.stdout }} run', register: sysbenchoutput, become: true}
  - {debug: 'msg="{{ sysbenchoutput.stdout }}"'}
