apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbit
  name: rabbit
spec:
  selector:
    matchLabels:
      io.kompose.service: rabbit
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: rabbit
    spec:
      containers:
      - image: rabbitmq:3.8-management
        name: rabbit
        imagePullPolicy: Always
        resources: {}
      restartPolicy: Always
status: {}
