apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: sure-tosca
  name: sure-tosca
spec:
  type: NodePort
  ports:
    - port: 8081
      nodePort: 30001
  selector:
    io.kompose.service: sure-tosca
status:
  loadBalancer: {}
