---
- hosts: all
  tasks:
  #- name: install pre-req
    #apt: name="{{ item }}" update_cache=yes state=latest
    #with_items: [git]
    #become: true
  - {name: git, command: 'git clone https://github.com/deviantony/docker-elk.git /tmp/docker-elk'}
  

  
  
  