version: "3.3"
services:
  monitor-server:
    image: salmant/ul_monitoring_server_container_image
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
      placement:
        constraints: [node.role == manager]
    environment:
      - MONITORING_SERVER=147.228.242.238
    ports:
      - "8080:8080"
      - "4242:4242"
      - "4245:4245"
      - "7199:7199"
      - "7000:7000"
      - "7001:7001"
      - "9160:9160"
      - "9042:9042"
      - "8012:8012"
      - "61621:61621"
    hostname: monitor-server
