apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: NAME
  name: NAME
  namespace: default
spec:
  selector:
   matchLabels:
    app: NAME
  replicas: 1
  template:
    metadata:
      labels:
        app: NAME
    spec:
      containers:
      - image: IMAGE_NAME
        name: NAME
        ports:
        - containerPort: PORT
        env:
        - name: ENV_NAME
          value: ENV_VAL
